services:

  server:
    build:
      dockerfile: server.Dockerfile
      context: .
    ports:
      - 1323:1323
    environment:
      PORT: "1323"
      API_ROOT: "https://api.coingecko.com/api/v3"
      ENDPOINT: "coins/markets"